version: '3.6'

services:
  elasticsearch:
    platform: linux/x86_64
    container_name: elasticsearch

    image: elasticsearch:7.9.3
    environment:
      - 'discovery.type=single-node'
    networks:
      - elasticnetwork
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana

    image: kibana:7.9.3
    networks:
      - elasticnetwork
    environment:
      - 'ELASTICSEARCH_HOST=elasticsearch'
      - 'ELASTICSEARCH_PORT=9200'

    ports:
      - 5601:5601

    depends_on:
      - elasticsearch

networks:
  elasticnetwork:
    driver: bridge
